spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password
      database: transactions
      authentication-database: admin
    jdbc:
      repositories:
        enabled: false

server:
  port: 8081